//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalAgendaSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaItems
    {
        public int AgendaItemId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public bool IsApproved { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
